center_crop = 512
linear_input = 8192
gpus = 1
batch_size = 8
num_workers = 0
save_dir = '~/jigsaw-puzzle-solver/results/logs/'
default_root_dir = '~/jigsaw-puzzle-solver/results/checkpoints/'
train_file = '~/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv/train.csv'
val_file = '~/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv/val.csv'
test_file = '~/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv/train.csv'
raw_img_path = '/data/jigsaw-puzzle-solver/raw_all/'
min_epochs = 1
max_epochs = 20
progress_bar_refresh_rate=0.5
learning_rate = 0.001
margin = 0.9
partial_conf=0
stage='train'
checkpoint_path=''
hparams_file=''
